### ISSUE TITLE
First event is always picked from the first half in Shuffle Mode

### ISSUE THREAD

**Issue by h0rn3z0r** [taburineagle/MPC-HC-Looper#11]
I was quite unhappy with shuffling and that's seems the main cause of it.

**Comment by taburineagle** [comment]
Ah, yes, you're right - I originally wrote the shuffling algorithm as taking each half of the events list, shuffling those individually several times, and then shuffling them back together like a deck of cards to force Looper to jump back and forth when shuffling... the new version doesn't work this way (it's just a standard randomizer), but I'll take a look at tinkering with the old version as well.
