### ISSUE TITLE
[Suggest] - Looper Is Working On KMPlayer 

### ISSUE THREAD

**Issue by Qutaiba-Khader** [taburineagle/MPC-HC-Looper#15]
Thanks for all of your work, but please can you open the gate [mpc*.exe] and let us select any exe ,
becuase your best looper is working on KMPlayer , but i need to rename the kmplayer.exe and select it every time 

Thanks again

**Comment by taburineagle** [comment]
Hello!  I actually wasn't aware that KMPlayer was a thing, so thanks for letting me know that.  Actually, you can choose any .exe - if you go back to the beginning where Looper asks where MPC-HC is (an easy way to do that is just to delete MPCLooper.ini), when it asks you to find the [mpc*.exe] file, just type "*.exe" in the "File Name" box, then hit ENTER, and Looper will allow you to select any *.exe file - this is what it looks like in the Firefox directory (just as an example):

![image](https://user-images.githubusercontent.com/18430526/144778712-0b34c624-db8c-4dd9-9542-179aeb839f6a.png)
