### ISSUE TITLE
Save as sidecar file with relative path

### ISSUE THREAD

**Issue by aybli** [taburineagle/MPC-HC-Looper#5]
I'd like to suggest an option to quickly save the looper file next to the video file with just the video filename as the path value.

e.g. open ".\example.mp4" in MPC-HC Looper, create an event "Event|1:10.000|1:20.000|example.mp4", then quickly save as ".\example.mp4.looper".

**Comment by taburineagle** [comment]
Hello!  That shouldn't be too hard to implement - I'd just need to write a check to see if there are only one or two events, then check to see if the filename is the same on all of the events, then use that base name as the looper file's default name when saving it.

**Comment by aybli** [comment]
Hey, I didn't even realize you could add multiple videos to one looper file! I would definitely appreciate it for my workflow but if it adds too much unnecessary complexity I get it and you may scratch that and I'll try it with some bash scripting instead.

**Comment by taburineagle** [comment]
Yep, events can use any file, so you can definitely add multiple media files to a .looper file.

**Feature added!**  What it does is check to see if you have one or more events - if you have one (or multiple, and the media paths for _every event_ is the same), the Save dialog chooses the relative path and name (+.looper) for the new looper file.  If you have events that use several different file paths, it just uses the traditional behavior.

https://github.com/taburineagle/MPC-HC-Looper/blob/master/bin/MPCLooper_RC_042720.exe?raw=true

**Comment by aybli** [comment]
Thank you so much, this works great!

**Comment by taburineagle** [comment]
Awesome!  Glad to be of service 😊
