### ISSUE TITLE
Doesn't save if a .looper file has hidden attribute

### ISSUE THREAD

**Issue by violinisten** [taburineagle/MPC-HC-Looper#6]
When editing 'hidden' .looper file after the "Do you want to overwrite the current .looper file?" prompt the edited file isn't overwritten and thus isn't saved. It works OK with normal 'unhidden' .looper files. 
MPCLooper_RC_070520 (all versions are affected however)
Windows 7 x64

**Comment by taburineagle** [comment]
Ahh, that's interesting - I haven't had to deal with hidden .looper files in the past, I wasn't aware they handled differently - I will take a look at this and see what I can do in the next few days!

**Comment by taburineagle** [comment]
OK, I committed a new version that should fix that - try this version:

https://github.com/taburineagle/MPC-HC-Looper/blob/master/bin/MPCLooper_RC_122320.exe

I'm also planning on re-writing Looper in Visual Basic, as AutoIt programs tend to show too many false-positives on VirusTotal - so this might be the last AutoIt version I release.

**Comment by violinisten** [comment]
Great. It works, thank you. Didn't know that to write to a hidden file AutoIt needs to unhide it first...
Good luck with language switching!

**Comment by taburineagle** [comment]
Ah, excellent - you're welcome!  I was unaware AutoIt handled hidden files that way too, but apparently there are a lot of Google results that say that, and the quick unhiding/rehiding method is the simplest way to get that to work properly.  Thanks as well on the new language - I have a prototype started now that does all of the Looper functions, I just need to work on getting the playlist functions sorted.
