### ISSUE TITLE
Window docking feature should consider taskbar location

### ISSUE THREAD

**Issue by h0rn3z0r** [taburineagle/MPC-HC-Looper#9]
I am using the top taskbar layout and currently MPC Lopper moves the player's window right under it when docking button is pressed. It would be probably better to center the window either horizontally only or both horizontally and vertically.

**Comment by taburineagle** [comment]
Ah, yes, you're correct - I hadn't taken the taskbar setting into account when writing that feature.  That shouldn't be too hard of an issue to fix, I just need to check for that value first before doing the dock, and move it down if it's laid out top-side.

**Comment by taburineagle** [comment]
OK, I wrote some procedures that should fix this - it fixes docking when the dock procedure is first launched - click the Left button and have the taskbar on the left, click the Right button and have the taskbar on the right, etc., it moves Looper/MPC-HC relative to the taskbar's current location.  I also compiled a new .exe so you can try this out - this .exe also fixes #7's issue - right-click here to download that - [MPC-HC Looper 03-19-21 RC .exe file](https://github.com/taburineagle/MPC-HC-Looper/blob/master/bin/MPCLooper_RC_031921.exe?raw=true)

**Comment by h0rn3z0r** [comment]
Thanks, it's working well :)
Should the fixed issues be closed now?

**Comment by taburineagle** [comment]
Ah, excellent!  Yes, I just wanted to make sure all was good on your end before closing them - will do that now.
